---
# tasks file for vm

- name: expand vda
  script: expand_vda.sh 
  tags: vm_init

- name: expand vdb
  script: expand_vdb.sh 
  tags: vm_init

- name: mount all 
  shell: mount -a
  tags: vm_init

- name: zabbix config
  shell: echo "Hostname=`hostname -s`" >> /etc/zabbix/zabbix_agentd.conf
  tags: vm_init
  notify:
  - restart zabbix-agent
