# tasks file for hypervisor

- name: libvirt install
  yum: name=libvirt-1.2.17-13.el7,qemu-kvm,virt-install state=present
  tags: hypervisor_init

- name: restart libvirt daemon
  service: name=libvirtd state=started enabled=yes
  tags: hypervisor_init

- name: stop virbr0
  virt_net: command=destroy name=default
  tags: hypervisor_init

- name: destroy virbr0
  virt_net: command=undefine name=default
  tags: hypervisor_init

- name: undefine virbr0
  shell: "{{ item }}"
  with_items:
  - virsh net-destroy default
  - virsh net-undefine default
  tags: hypervisor_init_original

- name: bridge configuration
  template: src=ifcfg-br0.j2 dest=/etc/sysconfig/network-scripts/ifcfg-br0
  tags: hypervisor_init

- name: nic configuration
  copy: src=ifcfg-eth0 dest=/etc/sysconfig/network-scripts/ifcfg-eth0
  tags: hypervisor_init

- name: libvirtd remote connection auth
  shell: "{{ item }}"
  with_items:
  - echo 'LIBVIRTD_ARGS="--listen"'  >> /etc/sysconfig/libvirtd
  - echo 'listen_tls = 0' >> /etc/libvirt/libvirtd.conf
  - echo 'listen_tcp = 1' >> /etc/libvirt/libvirtd.conf
  - echo freewheel | saslpasswd2 -a libvirt root
  notify:
  - restart libvirtd
  - restart network
  tags: hypervisor_init

- name: copy rhel template 
  copy: src=rhel_template 
