---
# tasks file for ipa
- name: ipa-client install 
  yum: name=ipa-client state=present
  tags: ipa_init

- name: lowercase hostname for ver 5
  shell: "{{ item }}"
  with_items:
  - hostname {{ ansible_nodename | lower }}
  - sed -i.bak "/^HOSTNAME/s/.*/HOSTNAME={{ ansible_nodename | lower }} /g" /etc/sysconfig/network
  when: ansible_distribution_major_version == "5"
  tags: name_lcase

- name: lowercase hostname for ver 7
  shell: "{{ item }}"
  with_items:
  - hostnamectl set-hostname {{ ansible_nodename | lower }}
  when: ansible_distribution_major_version == "7"
  tags: name_lcase

- name: ipa join for ver 7
  shell: ipa-client-install --server={{ ipa_server }} --nisdomain=fwmrm.net --domain={{ dns_domain }} --mkhomedir -w freewheel --unattended
  when: ansible_distribution_major_version == "7"
  tags: ipa_join

- name: ipa join for ver 5
  shell: "{{ item }}"
  with_items:
  - ipa-client-install --server={{ ipa_server }} --domain={{ dns_domain }} --mkhomedir -w freewheel --unattended --no-ntp
  when: ansible_distribution_major_version == "5"
  tags: ipa_join

- name: netgroup setup
  shell: "{{ item }}"
  with_items:
  - nisdomainname fwmrm.net
  - echo "NISDOMAIN=fwmrm.net" >> /etc/sysconfig/network
  tags: ipa_join_post

- name: install oddjob
  yum: name=oddjob state=present
  when: ansible_distribution_major_version == "7"
  tags: ipa_join_post
  notify:
  - restart oddjobd

- name: sssd configuration update
  shell: sed -i.bak '/^id_provider/a\entry_cache_sudo_timeout = 300' /etc/sssd/sssd.conf
  tags: ipa_join_post
  when: ansible_distribution_major_version == "7"
  notify:
  - restart sssd

- name: sudo for ver 5
  copy: src=ldap.conf dest=/etc/ldap.conf owner=root group=root mode=644 backup=yes
  when: ansible_distribution_major_version == "5"
  tags: ipa_join_post

- name: enable oddjobd
  service: name=oddjobd.service state=restarted enabled=yes
  when: ansible_distribution_major_version == "7"
  tags: ipa_join_post

- name: ssh configuration update
  shell: sed -i.bak '/^\s*GSSAPIAuth/a\\tGSSAPIDelegateCredentials yes' /etc/ssh/ssh_config
  tags: ipa_join_post

- name: bashrc update for stg
  copy: src=bashrc_template_stg dest=/etc/skel/.bashrc owner=root group=root mode=644 backup=yes
  when: env == "stg"
  tags: bashps

- name: root bashrc update for stg
  copy: src=bashrc_template_stg_root dest=/root/.bashrc owner=root group=root mode=644 backup=yes
  when: env == "stg"
  tags: bashps

- name: bashrc update for rnd
  copy: src=bashrc_template_rnd dest=/etc/skel/.bashrc owner=root group=root mode=644 backup=yes
  when: env == "rnd"
  tags: bashps

- name: root bashrc update for rnd
  copy: src=bashrc_template_rnd_root dest=/root/.bashrc owner=root group=root mode=644 backup=yes
  when: env == "rnd"
  tags: bashps
