---
# tasks file for openstack

- name: change root ssh key
  copy: src=root_key dest=/root/.ssh/authorized_keys owner=root group=root mode=644 backup=yes
  tags: ssh_key

- name: change ops ssh key
  copy: src=ops_key dest=/home/ops/.ssh/authorized_keys owner=ops group=ops mode=644 backup=yes
  tags: ssh_key

- name: sssd install
  yum: name=sssd,oddjob state=present 
  tags: ldap

- name: create sssd dir
  file: path=/etc/sssd state=directory mode=711
  tags: ldap

- name: krb5 config
  copy: src=krb5.conf dest=/etc/krb5.conf owner=root group=root mode=644
  tags: ldap

- name: sssd config
  copy: src=sssd.conf dest=/etc/sssd/sssd.conf owner=root group=root mode=600 
  tags: ldap

- name: enable sssd auth
  shell: "{{ item }}"
  with_items:
  - authconfig --enablesssd --enablesssdauth --enablemkhomedir --update
  - sed -i 's/\(^auth.*00.*\)/# \1/' /etc/pam.d/system-auth
  - sed -i 's/\(^auth.*00.*\)/# \1/' /etc/pam.d/password-auth
  notify:
  - restart sssd 
  tags: ldap

- name: enable oddjobd
  service: name=oddjobd.service state=restarted enabled=yes
  tags: ldap

- name: enable password ssh
  shell: sed -i.bak 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
  notify:
  - restart sshd
  tags: ssh
